#
# Linux Frame Buffer Device Configuration
#

CC =		gcc -Wall -O2 -I.
BISON =		bison -d
FLEX =		flex
INSTALL =	install
RM =		rm -f
DESTDIR =

All:		fbset con2fbmap

fbset:		fbset.o modes.tab.o lex.yy.o

fbset.o:	fbset.c fbset.h fb.h
modes.tab.o:	modes.tab.c fbset.h fb.h
lex.yy.o:	lex.yy.c fbset.h modes.tab.h

lex.yy.c:	modes.l
		$(FLEX) modes.l

modes.tab.c:	modes.y
		$(BISON) modes.y

con2fbmap:	con2fbmap.o
con2fbmap.o:	con2fbmap.c

install:	fbset
		# Frankly, let dpkg worry about that.
		#if [ -f /sbin/fbset ]; then rm /sbin/fbset; fi
		$(INSTALL) etc/fb.modes.ATI $(DESTDIR)/etc/fb.modes	
		$(INSTALL) fbset $(DESTDIR)/usr/sbin
		$(INSTALL) fbset.8 $(DESTDIR)/usr/share/man/man8
	 	$(INSTALL) modeline2fb $(DESTDIR)/usr/sbin	
		$(INSTALL) fb.modes.5 $(DESTDIR)/usr/share/man/man5
		$(INSTALL) con2fbmap $(DESTDIR)/usr/sbin
		$(INSTALL) con2fbmap.8 $(DESTDIR)/usr/share/man/man8
		# We handle this in the postinst.
		#if [ ! -c /dev/fb0 ]; then mknod /dev/fb0 c 29 0; fi
		#if [ ! -c /dev/fb1 ]; then mknod /dev/fb1 c 29 32; fi
		#if [ ! -c /dev/fb2 ]; then mknod /dev/fb2 c 29 64; fi
		#if [ ! -c /dev/fb3 ]; then mknod /dev/fb3 c 29 96; fi
		#if [ ! -c /dev/fb4 ]; then mknod /dev/fb4 c 29 128; fi
		#if [ ! -c /dev/fb5 ]; then mknod /dev/fb5 c 29 160; fi
		#if [ ! -c /dev/fb6 ]; then mknod /dev/fb6 c 29 192; fi
		#if [ ! -c /dev/fb7 ]; then mknod /dev/fb7 c 29 224; fi

clean:
		$(RM) *.o fbset con2fbmap lex.yy.c modes.tab.c modes.tab.h
