#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

#
# Only ask to create framebuffer devices if devfs isn't used.
#
if [ ! -c /dev/.devfsd ] ; then
  if [ ! -c /dev/fb0 ] ; then
    db_input medium fbset/create_framebuffer_devices || true
    db_go
  fi
fi
#DEBHELPER#
