#!/bin/sh -

set -e

# make sure /dev/fb*  exists
if ! test -c /dev/fb0
then
	cd /dev 
	./MAKEDEV fb
fi  

# update the menus for fbset (add)
# if test -x /usr/bin/update-menus
# then 
#	update-menus  
# fi
